<a href="https://colab.research.google.com/github/AswiniReddy19/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

In [1]:

%%time
N=100000
import numpy as np
arr = np.arange(N)
arr = arr *arr

CPU times: user 675 µs, sys: 1.07 ms, total: 1.74 ms
Wall time: 1.26 ms


# Creating np Arrays

In [2]:
arr = np.arange(10)
print(arr,type(arr))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [3]:
arr = np.array([1,1,3,9,2])
print(arr,type(arr))

[1 1 3 9 2] <class 'numpy.ndarray'>


In [4]:
arr

array([1, 1, 3, 9, 2])

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.size

5

In [8]:
arr.shape

(5,)

In [9]:
arr.itemsize

8

In [10]:
arr2d=np.array([
    [1,2,3],
    [7,8,9]
])

In [11]:
arr2d.dtype

dtype('int64')

In [12]:
arr2d.ndim

2

In [13]:
arr2d.size

6

In [14]:
arr2d.shape

(2, 3)

In [15]:
arr2d.itemsize

8

In [16]:
arr3d= np.array([
    [
        [2,3,4],
        [4,5,6]
    ],
    [
        [1,2,3],
        [6,7,8]
    ]

])

In [17]:
arr3d

array([[[2, 3, 4],
        [4, 5, 6]],

       [[1, 2, 3],
        [6, 7, 8]]])

In [18]:
arr3d.ndim

3

In [19]:
arr3d.shape

(2, 2, 3)

In [20]:
arr3d.dtype

dtype('int64')

In [21]:
arr3d.size

12

In [22]:
np.ones((2))

array([1., 1.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
123*np.ones((2,3,4))

array([[[123., 123., 123., 123.],
        [123., 123., 123., 123.],
        [123., 123., 123., 123.]],

       [[123., 123., 123., 123.],
        [123., 123., 123., 123.],
        [123., 123., 123., 123.]]])

In [26]:
 np.random.rand(2,3)

array([[0.39136605, 0.73761897, 0.37630194],
       [0.93830145, 0.96281062, 0.84796019]])

In [27]:
np.random.rand(2,4)

array([[0.75844273, 0.85001385, 0.38815891, 0.97108997],
       [0.91367267, 0.01459326, 0.5224111 , 0.97324992]])

In [28]:
np.random.rand(7,2)

array([[0.36341895, 0.24543439],
       [0.24641747, 0.77274214],
       [0.44437286, 0.31729992],
       [0.19469984, 0.38463825],
       [0.78997153, 0.42575897],
       [0.60196052, 0.61427433],
       [0.04633828, 0.34922064]])

In [29]:
np.random.randint(1,150,(3,4))

array([[12, 62, 74, 89],
       [14,  3, 72, 83],
       [94, 36, 64,  7]])

In [30]:
np.arange(1,30,5)

array([ 1,  6, 11, 16, 21, 26])

In [31]:
np.linspace(1,30,5)

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [32]:
np.linspace(7,70,7)

array([ 7. , 17.5, 28. , 38.5, 49. , 59.5, 70. ])

In [33]:
np.array([True,False,False,True])

array([ True, False, False,  True])

In [34]:
str_arr=np.array(['1.1','1.2','1.3'])

In [35]:
arr=np.array(str_arr,dtype='float')

In [36]:
arr

array([1.1, 1.2, 1.3])

# indexing

In [37]:
arr3d= np.array([
    [
        [2,3,4],
        [4,5,6]
    ],
    [
        [1,2,3],
        [6,7,8]
    ]

])

In [38]:
print(arr3d)

[[[2 3 4]
  [4 5 6]]

 [[1 2 3]
  [6 7 8]]]


In [39]:
arr3d[0 ,0 ,0]

np.int64(2)

In [40]:
arr3d[1, 0, 2]

np.int64(3)

In [41]:
i=1
j=0
k=2
arr3d[i,j,k]

np.int64(3)

In [42]:
i=0
print(i)

0


In [43]:
arr3d[0,:,:]

array([[2, 3, 4],
       [4, 5, 6]])

In [44]:
 arr3d[:,1,:]

array([[4, 5, 6],
       [6, 7, 8]])

In [45]:
arr3d[:,:,0:2]

array([[[2, 3],
        [4, 5]],

       [[1, 2],
        [6, 7]]])

In [46]:
arr3d % 2==0

array([[[ True, False,  True],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [47]:
arr3d[arr3d % 2==0]

array([2, 4, 4, 6, 2, 6, 8])

In [48]:
 arr3d[(arr3d % 2==0) & (arr3d > 3)]

array([4, 4, 6, 6, 8])

In [49]:
arr_slice = arr3d[:,:,0:2]
print(type(arr_slice))

<class 'numpy.ndarray'>


In [50]:
arr_slice.ndim

3

In [51]:
arr_slice.shape

(2, 2, 2)

In [52]:
arr_slice[0,0,1]

np.int64(3)

In [53]:
arr_slice[0,0,0] = 1729

In [54]:
arr_slice

array([[[1729,    3],
        [   4,    5]],

       [[   1,    2],
        [   6,    7]]])

In [55]:
arr3d

array([[[1729,    3,    4],
        [   4,    5,    6]],

       [[   1,    2,    3],
        [   6,    7,    8]]])

In [56]:
arr_slice = np.copy(arr3d[:,:,0:2])

In [57]:
arr_slice[0,0,0]=1

In [58]:
arr_slice

array([[[1, 3],
        [4, 5]],

       [[1, 2],
        [6, 7]]])

In [59]:
arr3d

array([[[1729,    3,    4],
        [   4,    5,    6]],

       [[   1,    2,    3],
        [   6,    7,    8]]])

In [60]:
arr =np.random.randint(0,10,(5))

In [61]:
arr

array([2, 0, 4, 9, 5])

In [62]:
my_indices = [1,3,4]


In [63]:
arr[my_indices]

array([0, 9, 5])

# Numpy operations

In [64]:
arr1=np.zeros((2,3))
arr2=np.ones((2,3))

In [65]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
arr1+arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
arr1 - arr2

array([[-1., -1., -1.],
       [-1., -1., -1.]])

In [68]:
arr1 *arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
arr1/arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.exp(arr1)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.log(arr2)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.sin(arr2)

array([[0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

In [73]:
np.cos(arr2)

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

In [74]:
np.sqrt(arr2)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
arr_inv = 1/arr2

In [76]:
arr_inv

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
arr1 = np.zeros((3,5))


In [78]:
arr_inv=1/arr1

/tmp/ipython-input-2737344192.py:1: RuntimeWarning: divide by zero encountered in divide
  arr_inv=1/arr1


In [79]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [80]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Exercise on finding numbers of points ouside n-dimensional sphere

In [81]:
ndim = 2
npoints =100000
points=np.random.rand(npoints,ndim)
points[0:2,:]

array([[0.51047426, 0.63606661],
       [0.73838589, 0.14041682]])

In [82]:
dfo=np.zeros((npoints,1))
outside_points=0

In [83]:
for i in range(npoints):
    for j in range(ndim):
        dfo[i]+=points[i,j]**2
    dfo[i] = np.sqrt(dfo[i])
    if dfo[i]>1:
        outside_points+=1

In [84]:
print('Fraction of points outside is',outside_points/npoints)

Fraction of points outside is 0.21249


In [85]:
1-(3.14)/4

0.21499999999999997

# Broadcasting

In [86]:
arr1 = np.arange(6)

In [87]:
arr1.shape

(6,)

In [88]:
arr1

array([0, 1, 2, 3, 4, 5])

In [89]:
arr1=arr1.reshape((2,3))

In [90]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
arr2=np.arange(6).reshape((2,3))

In [92]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [93]:
arr1+arr2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [94]:
arr2[0].reshape((1,3))

array([[0, 1, 2]])

In [95]:
arr1+arr2[0].reshape((1,3)) # (2,3)+((1,3))

array([[0, 2, 4],
       [3, 5, 7]])

In [96]:
arr1+arr2[:,0].reshape((2,1))

array([[0, 1, 2],
       [6, 7, 8]])

In [97]:
arr1+1

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr1=np.arange(24).reshape((2,3,4))

In [99]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [100]:
arr2=np.ones((1,4))

In [101]:
arr2

array([[1., 1., 1., 1.]])

In [102]:
arr1+arr2 #(2,3,4)+(1,4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [103]:
arr1=np.arange(4)

In [104]:
arr1

array([0, 1, 2, 3])

In [105]:
arr2=np.arange(5)

In [106]:
arr2

array([0, 1, 2, 3, 4])

In [107]:
print(arr1.shape,arr2.shape)

(4,) (5,)


In [110]:
arr1.reshape(4,1)+arr2 #(4,1)+(5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [111]:
arr1.T

array([0, 1, 2, 3])

In [112]:
arr=np.random.rand(3,3)

In [113]:
arr

array([[0.46726274, 0.090094  , 0.07095196],
       [0.32543029, 0.28249649, 0.36312765],
       [0.18078895, 0.07709664, 0.13837646]])

In [114]:
arr.T

array([[0.46726274, 0.32543029, 0.18078895],
       [0.090094  , 0.28249649, 0.07709664],
       [0.07095196, 0.36312765, 0.13837646]])

# File handling

In [117]:
small_planet=np.loadtxt("planets_small-200320-181217.txt",skiprows =1,
                        usecols = (1,2,3,4,5,6,7,8,9))

In [118]:
small_planet

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [119]:
small_planet.shape

(3, 9)

In [122]:
planets=np.genfromtxt("planets-200320-181217.txt",skip_header=1,usecols=[1,2,3,4,5,6,7,8,9])
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [123]:
planets.shape

(20, 9)

In [124]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [125]:
planets_new = np.nan_to_num(planets,nan = -1)
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [126]:
np.savetxt('planets_new.txt',planets_new,delimiter = '')

In [127]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [128]:
np.save("planets_new",planets_new)

In [129]:
!ls

cric_data-200320-181217.tsv  planets_new.npy  planets_small-200320-181217.txt
planets-200320-181217.txt    planets_new.txt  sample_data


In [130]:
arr1=np.random.rand(1000,10)
arr2=np.random.rand(2000,5)
arr3=np.random.rand(20,10000)

In [131]:
np.savez("many_arrs",arr1,arr2,arr3)

In [133]:
!ls

cric_data-200320-181217.tsv  planets_new.npy		      sample_data
many_arrs.npz		     planets_new.txt
planets-200320-181217.txt    planets_small-200320-181217.txt


In [134]:
#loading from multiple arrays
arrs=np.load("many_arrs.npz")
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [135]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [136]:
arrs['arr_0']

array([[0.512929  , 0.69034642, 0.49126025, ..., 0.17312906, 0.83895705,
        0.89004238],
       [0.39838636, 0.60599628, 0.40545116, ..., 0.1506324 , 0.36307111,
        0.8836441 ],
       [0.1401368 , 0.01290015, 0.95838952, ..., 0.71987147, 0.36985715,
        0.41095149],
       ...,
       [0.55164175, 0.31431641, 0.98394193, ..., 0.88342108, 0.11577256,
        0.06915035],
       [0.13884628, 0.92654807, 0.62081602, ..., 0.6026734 , 0.86455539,
        0.8618786 ],
       [0.39392817, 0.09550173, 0.83776038, ..., 0.36228875, 0.60651101,
        0.07278767]])

In [137]:
arrs['arr_0'].shape

(1000, 10)

In [138]:
np.savez_compressed('many_arrs_compressed',arr1,arr2,arr3)

In [139]:
!ls

cric_data-200320-181217.tsv  planets_new.npy
many_arrs_compressed.npz     planets_new.txt
many_arrs.npz		     planets_small-200320-181217.txt
planets-200320-181217.txt    sample_data


## statistical function of arrays using numpy

In [140]:
arr=np.random.rand(100000,)

In [141]:
np.amin(arr)

np.float64(2.6333611072848484e-06)

In [142]:
np.amax(arr)

np.float64(0.9999958538500432)

In [143]:
np.mean(arr)

np.float64(0.5003637646316353)

In [144]:
np.median(arr)

np.float64(0.5002159637604704)

In [145]:
np.var(arr)

np.float64(0.08351090412552022)

In [146]:
np.std(arr)

np.float64(0.2889825325612609)

In [147]:
np.percentile(arr,50)

np.float64(0.5002159637604704)

In [148]:
np.percentile(arr,10)

np.float64(0.10035757202324477)

In [149]:
np.percentile(arr,90)

np.float64(0.899446295862391)

In [150]:
#inter quartile range
iqr=np.percentile(arr,75)-np.percentile(arr,25)
print(iqr)

0.5021717584982054


In [151]:
# another way to fine iqr
quartile=np.percentile(arr,[25,75])
print(quartile)


[0.24959193 0.75176368]


In [152]:
iqr=quartile[1]=quartile[0]

In [153]:
print(iqr)

0.24959192602955949


In [154]:
print(arr-np.mean(arr)/np.std(arr))

[-0.76815838 -1.59450628 -1.53002264 ... -1.00815808 -1.10883001
 -0.79046558]


In [155]:
np.histogram(arr,bins=5)

(array([20044, 19924, 19984, 19912, 20136]),
 array([2.63336111e-06, 2.00001277e-01, 3.99999922e-01, 5.99998566e-01,
        7.99997210e-01, 9.99995854e-01]))

In [156]:
np.histogram(arr,bins=[0,0.25,0.5,0.75,1])

(array([25049, 24928, 24858, 25165]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [157]:
bins=[0,0.25,0.5,0.75,1]

In [158]:
np.digitize(arr,bins)

array([4, 1, 1, ..., 3, 3, 4])

In [159]:
arr1=np.random.randint(0,10,(10))
arr1

array([9, 9, 6, 9, 1, 8, 6, 0, 2, 0])

In [160]:
np.digitize(arr1,bins)

array([5, 5, 5, 5, 5, 5, 5, 1, 5, 1])

In [161]:
np.digitize(arr1,bins,right=True)

array([5, 5, 5, 5, 4, 5, 5, 0, 5, 0])

In [162]:
arr1=np.random.randint(50,80,100)
arr2=np.random.randint(150,185,100)
arr3=np.random.randint(17,22,100)

In [163]:
np.concatenate((arr1,arr2,arr3))

array([ 64,  61,  51,  50,  66,  69,  58,  65,  73,  77,  58,  56,  64,
        57,  70,  60,  79,  60,  68,  62,  64,  74,  70,  53,  78,  75,
        67,  61,  73,  61,  76,  65,  66,  58,  65,  59,  64,  52,  50,
        52,  63,  66,  69,  60,  64,  60,  77,  72,  74,  56,  78,  60,
        71,  63,  61,  65,  55,  62,  63,  50,  71,  63,  59,  60,  76,
        79,  68,  69,  75,  68,  66,  55,  53,  75,  50,  72,  61,  70,
        61,  75,  60,  64,  61,  68,  74,  70,  65,  63,  64,  62,  64,
        53,  52,  69,  51,  68,  50,  59,  52,  66, 170, 167, 180, 165,
       162, 178, 174, 156, 176, 154, 177, 152, 156, 150, 173, 166, 170,
       178, 160, 164, 158, 171, 178, 165, 160, 183, 150, 166, 180, 150,
       180, 184, 183, 169, 158, 159, 161, 171, 171, 155, 161, 174, 172,
       175, 179, 179, 152, 156, 172, 157, 179, 168, 184, 169, 175, 161,
       153, 156, 155, 177, 183, 180, 171, 178, 175, 173, 150, 183, 164,
       168, 151, 162, 159, 183, 171, 182, 182, 156, 182, 164, 15

In [164]:
np.concatenate((arr1,arr2,arr3)).shape

(300,)

In [165]:
np.amin(arr2d)

np.int64(1)

In [166]:
np.amin(arr2d,axis=1)

array([1, 7])

In [167]:
np.amax(arr2d,axis=1)

array([3, 9])

In [168]:
np.mean(arr2d,axis=1)

array([2., 8.])

## Rules of statistics

In [169]:
arr=np.random.rand(1000)
mean=np.mean(arr)
arr1=arr-mean
np.mean(arr1)

np.float64(6.039613253960852e-17)

In [170]:
arr=np.random.rand(1,50)
for k in range(1,50):
    arr1=arr[0:k]
    print(k,np.mean(arr1))

1 0.5620766737964438
2 0.5620766737964438
3 0.5620766737964438
4 0.5620766737964438
5 0.5620766737964438
6 0.5620766737964438
7 0.5620766737964438
8 0.5620766737964438
9 0.5620766737964438
10 0.5620766737964438
11 0.5620766737964438
12 0.5620766737964438
13 0.5620766737964438
14 0.5620766737964438
15 0.5620766737964438
16 0.5620766737964438
17 0.5620766737964438
18 0.5620766737964438
19 0.5620766737964438
20 0.5620766737964438
21 0.5620766737964438
22 0.5620766737964438
23 0.5620766737964438
24 0.5620766737964438
25 0.5620766737964438
26 0.5620766737964438
27 0.5620766737964438
28 0.5620766737964438
29 0.5620766737964438
30 0.5620766737964438
31 0.5620766737964438
32 0.5620766737964438
33 0.5620766737964438
34 0.5620766737964438
35 0.5620766737964438
36 0.5620766737964438
37 0.5620766737964438
38 0.5620766737964438
39 0.5620766737964438
40 0.5620766737964438
41 0.5620766737964438
42 0.5620766737964438
43 0.5620766737964438
44 0.5620766737964438
45 0.5620766737964438
46 0.56207667379644

In [171]:
arr=np.random.randint(1,100,100)

In [172]:
np.mean(arr)

np.float64(54.52)

In [173]:
np.median(arr)

np.float64(57.5)

In [174]:
arr=np.append(arr,[1000,2000])

In [175]:
arr.shape

(102,)

In [176]:
np.mean(arr)

np.float64(82.86274509803921)

In [177]:
np.median(arr)

np.float64(59.0)

In [178]:
arr=np.random.rand(100)

In [179]:
np.mean(arr)

np.float64(0.5388385303355056)

In [180]:
np.median(arr)

np.float64(0.5205113267656009)

In [181]:
arr1=2.5*arr+0.65

In [182]:
print(np.mean(arr1),2.5*np.mean(arr)+0.65)

1.997096325838764 1.997096325838764


In [183]:
print(np.var(2.5*arr+0.65),2.5*2.5*np.var(arr))

0.5612615881630332 0.5612615881630332


In [184]:
print(np.std(2.5*arr+0.65),2.5*np.std(arr))

0.7491739371888435 0.7491739371888434


In [185]:
arr1=np.random.rand(100)

In [186]:
arr2=np.random.rand(100)

In [187]:
print(np.mean(0.21*arr1-0.75*arr2),0.21*np.mean(arr1)-0.75*np.mean(arr2))

-0.25732040322813265 -0.25732040322813265
